---
# tasks file for install.cmake
- name: download cmake sources
  get_url:
    url: "https://cmake.org/files/v3.13/cmake-3.13.4.tar.gz"
    dest: ~/product
- name: unarchive cmake sources
  unarchive:
    src: ~/product/cmake-3.13.4.tar.gz
    dest: ~/
- name: run configure
  shell: ~/cmake-3.13.4/configure --prefix=/opt/cmake
  args:
    chdir: ~/cmake-3.13.4
- name: get number of core
  shell: nproc
  register: number_of_core
- name: compile cmake
  shell: cd ~/cmake-3.13.4 && make
- name: install cmake
  become: yes
  shell: ~/cmake-3.13.4/make install

